---
- name: Copy Docker Compose
  hosts: hostservers
  remote_user: root

  tasks:
  - name: Install
    ansible.builtin.yum:
      name: httpd
      state: latest
  - name: Update symlink
    ansible.builtin.file:
      path: path
      src: file destination
      dest: symlink location
      owner: foo
      group: foo
      state: symlink
